In [1]:
import glob
import tqdm.notebook as tq
import numpy as np
import pandas as pd
import cv2

In [2]:
from skimage.metrics import structural_similarity as ssim

In [3]:
from skimage.metrics import peak_signal_noise_ratio as psnr

In [ ]:
def updateColor(image):
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


In [4]:
def getMultiFramesPSNR(predImages, outImages):
    multiPSNRs = []
    for i in tq.tqdm( range(len(predImages)) ):
        multiPSNRs.append( psnr(predImages[i], outImages[i]) )
#     for pred, out in zip(predImages, outImages):
#         #ssim+=tf.image.ssim( input[i],GT[i], max_val=255, filter_size=11, filter_sigma=1.5, k1=0.01, k2=0.03)
#         multiPSNRs.append( psnr(pred, out) )
    return np.mean(multiPSNRs)

def getMultiFramesSSIM(predImages, outImages):
    multiSSIMs = []
    for i in tq.tqdm( range(len(predImages)) ):
        multiSSIMs.append( ssim(predImages[i], outImages[i], channel_axis=2) )
#     for pred, out in zip(predImages, outImages):
#         #ssim+=tf.image.ssim( input[i],GT[i], max_val=255, filter_size=11, filter_sigma=1.5, k1=0.01, k2=0.03)
#         multiSSIMs.append( ssim(pred, out, channel_axis=2) )
    return np.mean(multiSSIMs)

In [12]:
def getImages(location):
    Imgs = []
    currGlob = glob.glob( location )
    for img in (currGlob):
        Imgs.append( updateColor( cv2.resize( cv2.imread(img), (640, 360) ) ))
    return np.array(Imgs)
        
def calculateMetric(predLoc, outLoc):
    predictedImgs = getImages(predLoc)
    outImgs = getImages(outLoc)
    print(predictedImgs.shape, outImgs.shape)
    return getMultiFramesPSNR(predictedImgs, outImgs), getMultiFramesSSIM(predictedImgs, outImgs)

def executeEvaluation(predDir, outDir):
    allPSNRs = []
    allSSIMs = []
    testInfo = pd.read_csv(testDirectory + 'Info.csv', index_col=0) 
    for dr in testInfo['dirname'][1:]:
        print(dr)
        predLoc =  testDirectory + dr + '/' + predDir + '/*.jpg' 
        outDir  =  testDirectory + dr + '/' + outDir + '/*.jpg' 
        currPSNR, currSSIM = calculateMetric(predLoc, outDir)
        print(currPSNR, currSSIM)
        allPSNRs.append(currPSNR)
        allSSIMs.append(currSSIM)
    return allPSNRs, allSSIMs

In [6]:
testDirectory = 'DeepVideoDeblurring_Dataset/qualitative_datasets/'
testInfo = pd.read_csv(testDirectory + 'Info.csv', index_col=0)

In [7]:
allData = {}
for dr in testInfo['dirname']:
    lstmLoc =  testDirectory + dr + '/convLSTM/*.jpg'
    convLoc = testDirectory + dr + '/conv3d/*.jpg'
    outLoc  =  testDirectory + dr + '/ae_stabilize/*.jpg'
    
    lstmImgs = getImages(lstmLoc)
    convImgs = getImages(convLoc)
    outImgs  = getImages(outLoc)
    
    lstmPSNR = getMultiFramesPSNR(lstmImgs, outImgs)
    lstmSSIM = getMultiFramesSSIM(lstmImgs, outImgs)
    
    convPSNR = getMultiFramesPSNR(convImgs, outImgs)
    convSSIM = getMultiFramesSSIM(convImgs, outImgs)
    
    print(dr, convPSNR, convSSIM, lstmPSNR, lstmSSIM)
    allData[dr] = (convPSNR, convSSIM, lstmPSNR, lstmSSIM )

  0%|          | 0/258 [00:00<?, ?it/s]

  0%|          | 0/258 [00:00<?, ?it/s]

  0%|          | 0/258 [00:00<?, ?it/s]

  0%|          | 0/258 [00:00<?, ?it/s]

alley 24.36427606027114 0.7948209641866536 21.651468852766445 0.8038463911241976


  0%|          | 0/120 [00:00<?, ?it/s]

  0%|          | 0/120 [00:00<?, ?it/s]

  0%|          | 0/120 [00:00<?, ?it/s]

  0%|          | 0/120 [00:00<?, ?it/s]

anita 19.778652626490647 0.6365378256366391 18.576926662827834 0.6390870258575574


  0%|          | 0/156 [00:00<?, ?it/s]

  0%|          | 0/156 [00:00<?, ?it/s]

  0%|          | 0/156 [00:00<?, ?it/s]

  0%|          | 0/156 [00:00<?, ?it/s]

bicycle 17.914437998655 0.7776073357667561 18.270484259387125 0.8189590382815327


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

boat 19.919763439901825 0.6516251238389061 18.701799255132826 0.6882140583266336


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

books 19.40296665213297 0.7796608048031622 18.113944551521985 0.8086595255510418


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

bridge 16.876148605468178 0.6131916959950275 16.882824311968808 0.6717276641796168


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

camp 16.507929485106132 0.6659761220099482 16.974413125519575 0.7259146067924495


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

car 14.877958600826089 0.660266503138357 14.374915219992504 0.7103337343706525


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

cutting 16.20904171146923 0.7752633392911903 16.161133944268173 0.7861879495303681


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

kid 15.848507820614191 0.44374369253093016 16.045135256318773 0.5332052989457501


  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

metro 30.117388730322904 0.910039459316296 22.18873075177618 0.8434390075047905


  0%|          | 0/89 [00:00<?, ?it/s]

  0%|          | 0/89 [00:00<?, ?it/s]

  0%|          | 0/89 [00:00<?, ?it/s]

  0%|          | 0/89 [00:00<?, ?it/s]

office 18.068108908766984 0.7389868642125911 17.92076805789991 0.7600557687919779


  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

opera 16.189277501708776 0.6561497032111663 15.899258327725796 0.6847501060000585


  0%|          | 0/97 [00:00<?, ?it/s]

  0%|          | 0/97 [00:00<?, ?it/s]

  0%|          | 0/97 [00:00<?, ?it/s]

  0%|          | 0/97 [00:00<?, ?it/s]

piano 18.436142635938236 0.6177437720981005 17.208217937763937 0.6714175636024717


  0%|          | 0/163 [00:00<?, ?it/s]

  0%|          | 0/163 [00:00<?, ?it/s]

  0%|          | 0/163 [00:00<?, ?it/s]

  0%|          | 0/163 [00:00<?, ?it/s]

playground 18.397322170827046 0.6012536907505049 17.9612217194186 0.6628454927172172


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

quinault1 22.415898725682627 0.7304371900631756 22.153292602521653 0.746809696740447


  0%|          | 0/65 [00:00<?, ?it/s]

  0%|          | 0/65 [00:00<?, ?it/s]

  0%|          | 0/65 [00:00<?, ?it/s]

  0%|          | 0/65 [00:00<?, ?it/s]

street 17.32820792911559 0.7274560827966345 17.833964701008128 0.7726797319749167


  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

sup 20.867662357652204 0.67933314322025 18.860098373061543 0.7229598399796372


  0%|          | 0/240 [00:00<?, ?it/s]

  0%|          | 0/240 [00:00<?, ?it/s]

  0%|          | 0/240 [00:00<?, ?it/s]

  0%|          | 0/240 [00:00<?, ?it/s]

walk 20.762700970809025 0.7147289174008722 19.91800574402906 0.7563047432783699


In [11]:
a = np.array( list( allData.values() ) )

In [9]:
# Conv3d psnr, conv3d ssim, convlstm psnr, conv3d ssim
np.mean(a, axis=0)

array([19.17275752,  0.6934117 , 18.19455809,  0.72670512])

In [10]:
import json
with open('metric2.json', 'w+') as fp:
    json.dump(allData, fp)

In [51]:
PSNR(y, ypreds)

120


<tf.Tensor: shape=(), dtype=float32, numpy=inf>

In [38]:
getMetrics(inp, out)

258 258


(<tf.Tensor: shape=(), dtype=float32, numpy=inf>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)